blank_issues_enabled: false
contact_links:
  - name: 不知道怎么做?
    url: https://github.com/Mrs4s/go-cqhttp/issues/633
    about: 建议你先查看此教程
  - name: 讨论区
    url: https://github.com/Mrs4s/go-cqhttp/discussions/
    about: 使用中若遇到问题或有新点子新需求，请先在这里求助和征求意见。
