// Code generated by "stringer -type=Kind -trimprefix=Kind"; DO NOT EDIT.

package onebot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindAny-0]
	_ = x[KindBool-1]
	_ = x[KindDuration-2]
	_ = x[KindFloat64-3]
	_ = x[KindInt64-4]
	_ = x[KindString-5]
	_ = x[KindTime-6]
	_ = x[KindUint64-7]
	_ = x[KindGroup-8]
}

const _Kind_name = "AnyBoolDurationFloat64Int64StringTimeUint64Group"

var _Kind_index = [...]uint8{0, 3, 7, 15, 22, 27, 33, 37, 43, 48}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
