#!/usr/bin/env bash
function index.main_handler() {
    echo "Start GOCQHTTP~~~"
    cp -f config.yml /tmp/config.yml
    cp -f device.json /tmp/device.json
    ./go-cqhttp -w="/tmp/" faststart
}
index.main_handler
