#!/bin/sh
echo "Start GOCQHTTP~~~"
unset http_proxy
unset https_proxy

mkdir /mnt/
rm -rf /mnt/data/leveldb
cp -f config.yml /mnt/config.yml
cp -f device.json /mnt/device.json
./go-cqhttp -w="/mnt/" faststart
