name: Lint

on: [pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Tests
        run: |
          go test $(go list ./...)

      - name: Suggester
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: golangci-lint
